{% set version = "0.5.1" %}

package:
  name: statuspage
  version: {{ version }}

source:
  fn: python-statuspage-{{ version }}.tar.gz
  url: https://github.com/jayfk/statuspage/archive/{{ version }}.tar.gz
  sha256: 0a8ef33ac23efb6087a918a24cfc302482e14a72ed8bf547fcd0995e1bda5754

build:
  number: 0
  skip: true  # [win or py3k]

requirements:
  build:
    - curl
    - python
    - openssl
    - setuptools
    - packaging
    - pyinstaller
    - click
    - jinja2
    - tqdm
    - six

  run:
    - ca-certificates

test:
  commands:
    - statuspage --help

about:
  home: https://github.com/jayfk/statuspage
  license: MIT
  summary: A statuspage generator that lets you host your statuspage for free on Github.

extra:
  recipe-maintainers:
    - jakirkham
