{% set name = "statuspage" %}
{% set version = "0.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 354099766678b001a09b9950849acac23152aa4a4bc0f7e62949ca9df4dd331f

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  preserve_egg_dir: True
  entry_points:
    - statuspage=statuspage.statuspage:cli

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pygithub
    - click
    - jinja2
    - tqdm
    - requests
    - markdown2

test:
  commands:
    - statuspage --help

about:
  home: https://github.com/jayfk/statuspage
  license: MIT
  license_family: MIT
  summary: A statuspage generator that lets you host your statuspage for free on Github.

extra:
  recipe-maintainers:
    - jakirkham
